/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AYM.view;

import AYM.dao.UserDAO;
import AYM.model.AYmember;
import javax.swing.JOptionPane;

/**
 *
 * @author USER1
 */
public class AYM_SIGNUP extends javax.swing.JFrame {

    /**
     * Creates new form AYM_SIGNUP
     */
    public AYM_SIGNUP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signuppanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        signupbtn = new javax.swing.JButton();
        confirmpasswordfield = new javax.swing.JPasswordField();
        passwordfield = new javax.swing.JPasswordField();
        usernamefield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        rolecombo = new javax.swing.JComboBox<>();
        phonefield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        clubcombo = new javax.swing.JComboBox<>();
        backgroundlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signuppanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signuppanel.setMinimumSize(new java.awt.Dimension(1390, 850));
        signuppanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("SIGN UP");
        signuppanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 250, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("UserName:");
        signuppanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 200, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Phone Number:");
        signuppanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 230, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Role:");
        signuppanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 200, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Password:");
        signuppanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 200, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Confirm Password:");
        signuppanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 250, -1));

        signupbtn.setBackground(new java.awt.Color(255, 255, 102));
        signupbtn.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 28)); // NOI18N
        signupbtn.setText("REGISTER");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });
        signuppanel.add(signupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, -1, -1));
        signuppanel.add(confirmpasswordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 200, 40));
        signuppanel.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 200, 30));

        usernamefield.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signuppanel.add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 200, 40));

        jLabel7.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 255));
        jLabel7.setText("Already have an account?");
        signuppanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, -1, -1));

        loginbtn.setBackground(new java.awt.Color(255, 255, 255));
        loginbtn.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 22)); // NOI18N
        loginbtn.setText("LOG IN");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        signuppanel.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 620, -1, 40));

        rolecombo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rolecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN" }));
        rolecombo.setSelectedIndex(-1);
        rolecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolecomboActionPerformed(evt);
            }
        });
        signuppanel.add(rolecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 200, -1));
        signuppanel.add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 200, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Club:");
        signuppanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 70, 40));

        clubcombo.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        clubcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Master Guide", "Senior Youth", "Ambassodor", "Pathfinder", "Adventure" }));
        clubcombo.setSelectedIndex(-1);
        signuppanel.add(clubcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 200, 30));

        backgroundlabel.setBackground(new java.awt.Color(255, 255, 153));
        backgroundlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AYM/view/image/loginfinal1.png"))); // NOI18N
        signuppanel.add(backgroundlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signuppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signuppanel, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        AYMLOGIN login = new AYMLOGIN();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginbtnActionPerformed

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
            
        try{
        // making all field required
        if(usernamefield.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter username");
        }else if (usernamefield.getText().length()<5) {
                JOptionPane.showMessageDialog(this, "Please Username must be 5 characters");
            }else if(phonefield.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this,"Please enter Phone number");
        }else if (phonefield.getText().trim().length() != 10) {
        JOptionPane.showMessageDialog(this, "Phone number must be 10 digits long");
        }else if(rolecombo.getSelectedItem() == null){
        JOptionPane.showMessageDialog(this,"Please Select your role");
        }else if(clubcombo.getSelectedItem() == null){
        JOptionPane.showMessageDialog(this,"Please Select your club");
        }
        else if(passwordfield.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this,"Please enter Password");
        }else if(confirmpasswordfield.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this,"Please confirmPassword");
        }else{
            if (passwordfield.getText().equals(confirmpasswordfield.getText())) {
        if(passwordfield.getText().length()>=8){
            // lets capture data
            
            AYmember themember = new AYmember();
    themember.setUserName(usernamefield.getText());
    themember.setPhonenumber(phonefield.getText()); 
    themember.setPassword(passwordfield.getText());
    String selectedRole = (String) rolecombo.getSelectedItem();
    themember.setRole(selectedRole);
    String selectedClub = (String) clubcombo.getSelectedItem();
    themember.setClub(selectedClub);
//    themember.setConfirmpassword(confirmpasswordfield.getText());
            
            // call DAO
            UserDAO userdao = new UserDAO();
            Integer rowAffected = userdao.createUser(themember);
            if(rowAffected!= null){
            JOptionPane.showMessageDialog(this,"Member saved !! \n now you can go to log in");
            usernamefield.setText("");
                        phonefield.setText("");
                        passwordfield.setText("");
                        confirmpasswordfield.setText("");
                        rolecombo.setSelectedIndex(-1);
                        clubcombo.setSelectedIndex(-1);
            }else{
            JOptionPane.showMessageDialog(this, "Member not saved !!");
            } 
            
        }
        else{
              JOptionPane.showMessageDialog(this, "Password must be 8 characters!!");
                 }
            
        }
        
        }
        }catch(Exception ex )
        {ex.printStackTrace();}
    
        
    }//GEN-LAST:event_signupbtnActionPerformed

    private void rolecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolecomboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AYM_SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AYM_SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AYM_SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AYM_SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AYM_SIGNUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundlabel;
    private javax.swing.JComboBox<String> clubcombo;
    private javax.swing.JPasswordField confirmpasswordfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JTextField phonefield;
    private javax.swing.JComboBox<String> rolecombo;
    private javax.swing.JButton signupbtn;
    private javax.swing.JPanel signuppanel;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
