/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AYM.view;

import AYM.dao.UserDAO;
import AYM.model.AYmember;
import javax.swing.JOptionPane;

/**
 *
 * @author USER1
 */
public class AYMRecovery extends javax.swing.JFrame {

    /**
     * Creates new form AYMRecovery
     */
    public AYMRecovery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recoverypanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newpasswordfield = new javax.swing.JPasswordField();
        confirmpasswordfield = new javax.swing.JPasswordField();
        usernamefield = new javax.swing.JTextField();
        submitbtn = new javax.swing.JButton();
        loginbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        signupbtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        recoverypanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("CHANGE PASSWORD");
        recoverypanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("UserName:");
        recoverypanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 210, 50));

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("New Password:");
        recoverypanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 240, 50));

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Confirm Password:");
        recoverypanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, 53));
        recoverypanel.add(newpasswordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 200, 40));

        confirmpasswordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpasswordfieldActionPerformed(evt);
            }
        });
        recoverypanel.add(confirmpasswordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 200, 40));

        usernamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamefieldActionPerformed(evt);
            }
        });
        recoverypanel.add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 200, 40));

        submitbtn.setBackground(new java.awt.Color(255, 255, 51));
        submitbtn.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 28)); // NOI18N
        submitbtn.setText("SUBMIT");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        recoverypanel.add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        loginbtn.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 20)); // NOI18N
        loginbtn.setText("LOG IN");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        recoverypanel.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 110, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Already have an account?");
        recoverypanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, 40));

        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Don't have an account?");
        recoverypanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 493, 260, 30));

        signupbtn.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 20)); // NOI18N
        signupbtn.setText("SIGN UP");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });
        recoverypanel.add(signupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AYM/view/image/recovery wallpaper.png"))); // NOI18N
        recoverypanel.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1030, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recoverypanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recoverypanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
                                         
                                            
    String username = usernamefield.getText().trim();
    String newPassword = new String(newpasswordfield.getPassword());
    String confirmPassword = new String(confirmpasswordfield.getPassword());

    if (username.isEmpty() || newPassword.isEmpty() || confirmPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields");
    } else if (!newPassword.equals(confirmPassword)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match");
    } else {
        try {
            AYmember member = new AYmember();
            member.setUserName(username);
            member.setPassword(newPassword);
            
            UserDAO userdao = new UserDAO();
            boolean passwordUpdated = userdao.updatePassword(member);
            if (passwordUpdated) {
                JOptionPane.showMessageDialog(this, "Password updated successfully");
              
                usernamefield.setText("");
                newpasswordfield.setText("");
                confirmpasswordfield.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update password");
                usernamefield.setText("");
                newpasswordfield.setText("");
                confirmpasswordfield.setText("");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred");
        }
    }

    }//GEN-LAST:event_submitbtnActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
            AYMLOGIN login = new AYMLOGIN();
            login.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_loginbtnActionPerformed

    private void confirmpasswordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpasswordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpasswordfieldActionPerformed

    private void usernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamefieldActionPerformed

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
       AYM_SIGNUP signup = new AYM_SIGNUP();
       signup.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_signupbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AYMRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AYMRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AYMRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AYMRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AYMRecovery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPasswordField confirmpasswordfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField newpasswordfield;
    private javax.swing.JPanel recoverypanel;
    private javax.swing.JButton signupbtn;
    private javax.swing.JButton submitbtn;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
