/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AYM.view;

import AYM.dao.ClubDAO;
import AYM.model.AYclub;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER1
 */
public class Clubmanagementpageadmin extends javax.swing.JFrame {
DefaultTableModel clubtableModel = new DefaultTableModel();
 private void addColumnsHeaderNameToClubTable(){
        clubtableModel.addColumn("Club ID");
        clubtableModel.addColumn("Club Name");
        clubtableModel.addColumn("Club Description");
       clubtable.setModel(clubtableModel);
       clubtable.getTableHeader().setReorderingAllowed(false);
       clubtable.getTableHeader().setResizingAllowed(false);
    }
 
  private void addrowsclubdata() {
    clubtableModel.setRowCount(0); 
    ClubDAO clubdao = new ClubDAO();
    List<AYclub> ayclub = clubdao.retrieveallclubs();
    for (AYclub club : ayclub) {
        clubtableModel.addRow(new Object[]{
            club.getClubId(),
            club.getClubname(),
            club.getDescription()
        });
    }
}
    /**
     * Creates new form Clubmanagementpageadmin
     */
    public Clubmanagementpageadmin() {
        initComponents();
        addColumnsHeaderNameToClubTable();
         addrowsclubdata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clubtab = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        clubidfield = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        updateclubbtn = new javax.swing.JButton();
        deleteclubbtn = new javax.swing.JButton();
        clubidtosearch = new javax.swing.JTextField();
        searchclubtn = new javax.swing.JButton();
        refreshclub = new javax.swing.JButton();
        descriptioncombo = new javax.swing.JComboBox<>();
        saveclubbtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        clubnamecombo = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        clubtable = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 200));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(984, 566));

        clubtab.setBackground(new java.awt.Color(204, 204, 204));

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel12.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 23)); // NOI18N
        jLabel12.setText("Club Information");

        jLabel15.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Club ID:");

        jLabel16.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Description:");

        clubidfield.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clubidfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubidfieldActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel18.setText("Club's Id");

        updateclubbtn.setBackground(new java.awt.Color(51, 51, 51));
        updateclubbtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        updateclubbtn.setForeground(new java.awt.Color(0, 153, 255));
        updateclubbtn.setText("Update");
        updateclubbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateclubbtnActionPerformed(evt);
            }
        });

        deleteclubbtn.setBackground(new java.awt.Color(51, 51, 51));
        deleteclubbtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        deleteclubbtn.setForeground(new java.awt.Color(0, 153, 255));
        deleteclubbtn.setText("Delete");
        deleteclubbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteclubbtnActionPerformed(evt);
            }
        });

        searchclubtn.setBackground(new java.awt.Color(51, 51, 51));
        searchclubtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        searchclubtn.setForeground(new java.awt.Color(0, 153, 255));
        searchclubtn.setText("Search");
        searchclubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchclubtnActionPerformed(evt);
            }
        });

        refreshclub.setBackground(new java.awt.Color(51, 51, 51));
        refreshclub.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        refreshclub.setForeground(new java.awt.Color(0, 153, 255));
        refreshclub.setText("Refresh");
        refreshclub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshclubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refreshclub)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(updateclubbtn)
                                .addComponent(searchclubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deleteclubbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(clubidtosearch, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(55, 55, 55))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clubidtosearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(searchclubtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateclubbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteclubbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshclub)
                .addGap(9, 9, 9))
        );

        descriptioncombo.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        descriptioncombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3-9years", "10-15years", "16-21years", "22-99years" }));
        descriptioncombo.setSelectedIndex(-1);

        saveclubbtn.setBackground(new java.awt.Color(51, 51, 51));
        saveclubbtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        saveclubbtn.setForeground(new java.awt.Color(0, 153, 255));
        saveclubbtn.setText("Save");
        saveclubbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveclubbtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Club Name:");

        clubnamecombo.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        clubnamecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senior youth", "Ambassodor", "Pathfinder", "Adventures" }));
        clubnamecombo.setSelectedIndex(-1);

        jLabel19.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        jLabel19.setText("Club DataTable");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(249, 249, 249))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(saveclubbtn)
                                .addGap(35, 35, 35)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(clubidfield)
                                .addComponent(descriptioncombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clubnamecombo, 0, 170, Short.MAX_VALUE)))
                        .addGap(84, 84, 84)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clubidfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clubnamecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(descriptioncombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveclubbtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        clubtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(clubtable);

        jLabel22.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 28)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 51, 255));
        jLabel22.setText("CLUB MANAGEMENT");

        closebtn.setBackground(new java.awt.Color(255, 204, 51));
        closebtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AYM/view/image/close.png"))); // NOI18N
        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clubtabLayout = new javax.swing.GroupLayout(clubtab);
        clubtab.setLayout(clubtabLayout);
        clubtabLayout.setHorizontalGroup(
            clubtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clubtabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(clubtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(clubtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(clubtabLayout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addGap(268, 268, 268)
                            .addComponent(closebtn))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        clubtabLayout.setVerticalGroup(
            clubtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clubtabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clubtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clubtab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(clubtab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clubidfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubidfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clubidfieldActionPerformed

    private void updateclubbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateclubbtnActionPerformed
        try {
            // Get the updated data from the UI fields
            String clubid = clubidfield.getText();
            String aclubname = (String) clubnamecombo.getSelectedItem();
            String clubdescription= (String) descriptioncombo.getSelectedItem();

            // Create a club object with updated data
            AYclub updatedclub = new AYclub();
            updatedclub.setClubId(Integer.parseInt(clubid));
            updatedclub.setClubname(aclubname);
            updatedclub.setDescription(clubdescription);
            ClubDAO dao = new ClubDAO();
            int rowsAffected = dao.updateclub(updatedclub);
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "club updated successfully");
                clubidfield.setText("");
                clubnamecombo.setSelectedIndex(-1);
                descriptioncombo.setSelectedIndex(-1);
                addrowsclubdata();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update club");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_updateclubbtnActionPerformed

    private void deleteclubbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteclubbtnActionPerformed
        try {
            String clubIdToDelete = clubidfield.getText();
            if (clubIdToDelete.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the club ID to delete.");
                return;
            }
            int confirmDialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this club?",
                "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if (confirmDialogResult == JOptionPane.YES_OPTION) {
                int clubId = Integer.parseInt(clubIdToDelete);
                AYclub clubToDelete = new AYclub();
                clubToDelete.setClubId(clubId);

                ClubDAO dao = new ClubDAO();
                int rowsAffected = dao.deleteClub(clubToDelete);
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Club deleted successfully.");
                    clubidfield.setText("");
                    clubnamecombo.setSelectedIndex(-1);
                    descriptioncombo.setSelectedIndex(-1);
                    addrowsclubdata();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete club. Club not found or an error occurred.");
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
    }//GEN-LAST:event_deleteclubbtnActionPerformed

    private void searchclubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchclubtnActionPerformed
        try{
            if (clubidtosearch.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Club ID to search is required");
            } else {
                int clubId = Integer.parseInt(clubidtosearch.getText());
                AYclub club = new AYclub();
                club.setClubId(clubId);
                ClubDAO clubdao = new ClubDAO();
                // i am going to use status to check and continue if true
                int status = clubdao.findClubById(club);
                if (status == 1) {
                    clubidfield.setText(Integer.toString(club.getClubId()));
                    clubnamecombo.setSelectedItem(club.getClubname());
                    descriptioncombo.setSelectedItem(club.getDescription());

                    clubidfield.setEditable(rootPaneCheckingEnabled);
                } else {
                    JOptionPane.showMessageDialog(this, "Club not found");
                }

            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_searchclubtnActionPerformed

    private void refreshclubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshclubActionPerformed
        try {
            
        ClubDAO clubdao = new ClubDAO();
        List<AYclub> clubList = clubdao.retrieveallclubs(); 
        DefaultTableModel clubmodel = (DefaultTableModel) clubtable.getModel();
        clubmodel.setRowCount(0); // Clear the table
        for (AYclub club : clubList) {
             clubmodel.addRow(new Object[]{club.getClubId(), club.getClubname(), club.getDescription()});
        }
    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_refreshclubActionPerformed

    private void saveclubbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveclubbtnActionPerformed
        try{
            boolean condition= true;
            if(clubidfield.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID is required");
            }else if(clubnamecombo.getSelectedItem()== null){
                JOptionPane.showMessageDialog(this,"Please select club name");
            }else if(descriptioncombo.getSelectedItem()== null){
                JOptionPane.showMessageDialog(this,"Please enter description");
            }if(clubidfield.getText().length()==5){
                AYclub theclub = new AYclub();
                int id = Integer.parseInt(clubidfield.getText());
                theclub.setClubId(id);
                String selectedname = (String) clubnamecombo.getSelectedItem();
                theclub.setClubname(selectedname);
                String selecteddescription = (String) descriptioncombo.getSelectedItem();
                theclub.setDescription(selecteddescription);
                ClubDAO clubdao = new ClubDAO();
                Integer rowAffected = clubdao.createClub(theclub);
                if(rowAffected!= null){
                    JOptionPane.showMessageDialog(this,"Club saved !!");
                    clubidfield.setText("");
                    clubnamecombo.setSelectedIndex(-1);
                    descriptioncombo.setSelectedIndex(-1);
                    addrowsclubdata();
                }else{
                    JOptionPane.showMessageDialog(this, "Club not saved !!");
                }
            }else{
                JOptionPane.showMessageDialog(this, "club id must be 5 numbers!!");
            }

        }catch(Exception ex){
            ex.printStackTrace();}
    }//GEN-LAST:event_saveclubbtnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clubmanagementpageadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clubmanagementpageadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clubmanagementpageadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clubmanagementpageadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clubmanagementpageadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebtn;
    private javax.swing.JTextField clubidfield;
    private javax.swing.JTextField clubidtosearch;
    private javax.swing.JComboBox<String> clubnamecombo;
    private javax.swing.JPanel clubtab;
    private javax.swing.JTable clubtable;
    private javax.swing.JButton deleteclubbtn;
    private javax.swing.JComboBox<String> descriptioncombo;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshclub;
    private javax.swing.JButton saveclubbtn;
    private javax.swing.JButton searchclubtn;
    private javax.swing.JButton updateclubbtn;
    // End of variables declaration//GEN-END:variables
}
