/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AYM.view;

import AYM.dao.EventDAO;
import AYM.model.AYevent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER1
 */
public class eventsmanagementpageadmin extends javax.swing.JFrame {
  
    DefaultTableModel eventtablemodel = new DefaultTableModel();
    
    private void addColumnsHeaderNameToEventTable(){
    eventtablemodel.addColumn("Event ID");
    eventtablemodel.addColumn("Event Name");
    eventtablemodel.addColumn("Date");
    eventtablemodel.addColumn("Location");
    eventtablemodel.addColumn("Organiser");
    eventstable.setModel(eventtablemodel);
    eventstable.getTableHeader().setReorderingAllowed(false);
    eventstable.getTableHeader().setResizingAllowed(false);
    }
    
     private void addrowseventdata() {
    eventtablemodel.setRowCount(0); 
    EventDAO eventdao = new EventDAO();
    List<AYevent> ayevent =eventdao.retrieveallevents();
    for (AYevent event : ayevent) {
        eventtablemodel.addRow(new Object[]{
            event.getEventId(),
            event.getEventName(),
            event.getEventdate(),
            event.getEventdate(),
            event.getEventlocation(),
            event.getEventorganiser()
        });
    }
}
      public void refreshevent(){
       EventDAO eventdao = new EventDAO();
        List<AYevent> eventList = eventdao.retrieveallevents(); 
        DefaultTableModel eventmodel = (DefaultTableModel) eventstable.getModel();
        eventmodel.setRowCount(0); // Clear the table
        for (AYevent event : eventList) {
             eventmodel.addRow(new Object[]{event.getEventId(), event.getEventName(), event.getEventdate()
             ,event.getEventlocation(),event.getEventorganiser()});
        }
    }
    /**
     * Creates new form eventsmanagementpageadmin
     */
    public eventsmanagementpageadmin() {
        initComponents();
        addColumnsHeaderNameToEventTable();
        addrowseventdata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventtab = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        eventidfield = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        eventnamefield = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        datefield = new javax.swing.JFormattedTextField();
        jLabel30 = new javax.swing.JLabel();
        locationeventfield = new javax.swing.JTextField();
        addeventbtn = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        organisercombo = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        searcheventfield = new javax.swing.JTextField();
        searcheventbtn = new javax.swing.JButton();
        updateeventbtn = new javax.swing.JButton();
        deleteeventbtn = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        eventstable = new javax.swing.JTable();
        closebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 200));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(984, 566));

        eventtab.setBackground(new java.awt.Color(204, 204, 204));

        jPanel6.setBackground(new java.awt.Color(51, 102, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));

        jLabel28.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Event Id:");

        jLabel25.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Event Name:");

        jLabel26.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Date & Time:");

        datefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datefieldActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Location/Venue:");

        addeventbtn.setBackground(new java.awt.Color(255, 204, 51));
        addeventbtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        addeventbtn.setText("Add Event");
        addeventbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addeventbtnActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 51, 255));
        jLabel32.setText("Event Information");

        organisercombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MasterGuide", "Club leader" }));
        organisercombo.setSelectedIndex(-1);

        jLabel29.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Organiser:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(33, 33, 33)
                                .addComponent(eventidfield, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eventnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel30)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(organisercombo, 0, 236, Short.MAX_VALUE)
                            .addComponent(locationeventfield))
                        .addGap(18, 18, 18))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addeventbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventidfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(eventnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationeventfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organisercombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addeventbtn))
        );

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel13.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 21)); // NOI18N
        jLabel13.setText("Enter event id or Date:");

        searcheventbtn.setBackground(new java.awt.Color(255, 204, 51));
        searcheventbtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        searcheventbtn.setText("Search");
        searcheventbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcheventbtnActionPerformed(evt);
            }
        });

        updateeventbtn.setBackground(new java.awt.Color(255, 204, 51));
        updateeventbtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        updateeventbtn.setText("Edit Event");
        updateeventbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateeventbtnActionPerformed(evt);
            }
        });

        deleteeventbtn.setBackground(new java.awt.Color(255, 204, 51));
        deleteeventbtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        deleteeventbtn.setText("Delete Event");
        deleteeventbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteeventbtnActionPerformed(evt);
            }
        });

        refresh.setBackground(new java.awt.Color(255, 204, 51));
        refresh.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(34, 34, 34))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteeventbtn)
                            .addComponent(searcheventfield, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searcheventbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(updateeventbtn))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(refresh)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searcheventfield, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(searcheventbtn)
                .addGap(7, 7, 7)
                .addComponent(updateeventbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteeventbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refresh)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel33.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        jLabel33.setText("Events DataTable");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addGap(8, 8, 8))
        );

        jLabel23.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 22)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 255));
        jLabel23.setText("EVENT MANAGEMENT");

        eventstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(eventstable);

        closebtn.setBackground(new java.awt.Color(255, 204, 51));
        closebtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AYM/view/image/close.png"))); // NOI18N
        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eventtabLayout = new javax.swing.GroupLayout(eventtab);
        eventtab.setLayout(eventtabLayout);
        eventtabLayout.setHorizontalGroup(
            eventtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventtabLayout.createSequentialGroup()
                .addGroup(eventtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eventtabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(eventtabLayout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(jLabel23)
                        .addGap(211, 211, 211)
                        .addComponent(closebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34)))
                .addContainerGap())
            .addGroup(eventtabLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eventtabLayout.setVerticalGroup(
            eventtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eventtabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eventtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eventtabLayout.createSequentialGroup()
                        .addComponent(closebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eventtabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(eventtab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 26, Short.MAX_VALUE)
                    .addComponent(eventtab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 27, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datefieldActionPerformed

    private void addeventbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addeventbtnActionPerformed
        try {
            if (eventidfield.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter Id!!!");
            }else if(datefield.getText().trim().isEmpty() ){
                JOptionPane.showMessageDialog(this, "Please enter date!!!");
                String date = datefield.getText();
                if (!date.matches("\\d{2}-\\d{2}-\\d{4},\\d{2}:\\d{2}")) {
                    JOptionPane.showMessageDialog(this, "Invalid date format. Please use DD-MM-YYYY,HH:MM");
                }
            }else if(locationeventfield.getText().trim().isEmpty() ){
                JOptionPane.showMessageDialog(this, "Please enter location!!");
            }
            if(eventidfield.getText().trim().length() == 3){
                AYevent theevent = new AYevent();
                theevent.setEventId(Integer.parseInt(eventidfield.getText()));
                theevent.setEventName(eventnamefield.getText());
                theevent.setEventdate(datefield.getText());
                theevent.setEventlocation(locationeventfield.getText());
                String selectedname = (String) organisercombo.getSelectedItem();
                theevent.setEventorganiser(selectedname);
                EventDAO eventdao = new EventDAO();
                int rowAffected = eventdao.createEvent(theevent);
                if (rowAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Event created successfully");
                    eventidfield.setText("");
                    eventnamefield.setText("");
                    datefield.setText("");
                    locationeventfield.setText("");
                    organisercombo.setSelectedIndex(-1);
                    refreshevent();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to create Event!!");
                }
            }else{
                JOptionPane.showMessageDialog(this, "event id must be 3 numbers!!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_addeventbtnActionPerformed

    private void searcheventbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcheventbtnActionPerformed
        try{
            if (searcheventfield.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Event ID to search is required");
            } else {
                int eventId = Integer.parseInt(searcheventfield.getText());
                AYevent event = new AYevent();
                event.setEventId(eventId);
                EventDAO dao = new EventDAO();
                // i am going to use status to check and continue if true
                int status = dao.findEventById(event);
                if (status == 1) {

                    eventidfield.setText(Integer.toString(event.getEventId()));
                    eventnamefield.setText(event.getEventName());
                    datefield.setText(event.getEventdate());
                    locationeventfield.setText(event.getEventlocation());
                    organisercombo.setSelectedItem(event.getEventorganiser());

                    eventidfield.setEditable(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Event not found");
                }

            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_searcheventbtnActionPerformed

    private void updateeventbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateeventbtnActionPerformed
        try {
            // Capture data from input fields
            int eventId = Integer.parseInt(eventidfield.getText());
            String eventName = eventnamefield.getText();
            String eventDate = datefield.getText();
            String eventLocation = locationeventfield.getText();
            String eventOrganiser = (String) organisercombo.getSelectedItem();

            // Check if any required field is empty
            if (eventidfield.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter ID!!!");
            }else if (eventnamefield.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter name!!!");
            } else if (datefield.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter date!!!");
            } else if (locationeventfield.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter location!!");
            } else {
                // Check date format
                if (!eventDate.matches("\\d{2}-\\d{2}-\\d{4},\\d{2}:\\d{2}")) {
                    JOptionPane.showMessageDialog(this, "Invalid date format. Please use DD-MM-YYYY, HH:MM");
                    return; // Stop further processing
                }

                // Create AYevent object
                AYevent updateEvent = new AYevent();
                updateEvent.setEventId(eventId);
                updateEvent.setEventName(eventName);
                updateEvent.setEventdate(eventDate);
                updateEvent.setEventlocation(eventLocation);
                updateEvent.setEventorganiser(eventOrganiser);

                // Create EventDAO instance and update the event
                EventDAO dao = new EventDAO();
                int rowsAffected = dao.updateevent(updateEvent);

                // Check if the update was successful
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Event updated successfully");

                    // Clear input fields
                    eventidfield.setText("");
                    eventnamefield.setText("");
                    datefield.setText("");
                    locationeventfield.setText("");
                    organisercombo.setSelectedIndex(-1);
                    refreshevent();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to update event");
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid Event ID. Please enter a valid integer.");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_updateeventbtnActionPerformed

    private void deleteeventbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteeventbtnActionPerformed
        try {
            String eventIdToDelete = eventidfield.getText();

            if (eventIdToDelete.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the event ID to delete.");
                return;
            }

            int confirmDialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this event?",
                "Confirm Deletion", JOptionPane.YES_NO_OPTION);

            if (confirmDialogResult == JOptionPane.YES_OPTION) {
                int eventId = Integer.parseInt(eventIdToDelete);
                AYevent eventToDelete = new AYevent();
                eventToDelete.setEventId(eventId);

                EventDAO dao = new EventDAO();
                int rowsAffected = dao.deleteEvent(eventToDelete);

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Event deleted successfully.");
                    eventidfield.setText("");
                    eventnamefield.setText("");
                    datefield.setText("");
                    locationeventfield.setText("");
                    organisercombo.setSelectedIndex(-1);
                    refreshevent();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete event. Event not found or an error occurred.");
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_deleteeventbtnActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        try {
            refreshevent();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_refreshActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eventsmanagementpageadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eventsmanagementpageadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eventsmanagementpageadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eventsmanagementpageadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eventsmanagementpageadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addeventbtn;
    private javax.swing.JButton closebtn;
    private javax.swing.JFormattedTextField datefield;
    private javax.swing.JButton deleteeventbtn;
    private javax.swing.JTextField eventidfield;
    private javax.swing.JTextField eventnamefield;
    private javax.swing.JTable eventstable;
    private javax.swing.JPanel eventtab;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField locationeventfield;
    private javax.swing.JComboBox<String> organisercombo;
    private javax.swing.JButton refresh;
    private javax.swing.JButton searcheventbtn;
    private javax.swing.JTextField searcheventfield;
    private javax.swing.JButton updateeventbtn;
    // End of variables declaration//GEN-END:variables
}
