/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AYM.view;

/**
 *
 * @author USER1
 */

public class RegularUserDashboard extends javax.swing.JFrame {
 
    
    
     
    public RegularUserDashboard() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Parentpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        homebtn = new javax.swing.JButton();
        myprofilebtn = new javax.swing.JButton();
        eventbtn = new javax.swing.JButton();
        materialsbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Parentpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Parentpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(250, 250, 250));
        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADVENTIST YOUTH ");
        Parentpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, 40));

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MANAGEMENT SYSTEM");
        Parentpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        homebtn.setBackground(new java.awt.Color(153, 153, 153));
        homebtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        homebtn.setForeground(new java.awt.Color(51, 255, 51));
        homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AYM/view/image/Customer Registration & Check IN.png"))); // NOI18N
        homebtn.setText("HOME");
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        Parentpanel.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 40, -1, -1));

        myprofilebtn.setBackground(new java.awt.Color(153, 153, 153));
        myprofilebtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        myprofilebtn.setForeground(new java.awt.Color(0, 153, 255));
        myprofilebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AYM/view/image/pngwing.com (1).png"))); // NOI18N
        myprofilebtn.setText("My profile");
        myprofilebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myprofilebtnMouseClicked(evt);
            }
        });
        myprofilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myprofilebtnActionPerformed(evt);
            }
        });
        Parentpanel.add(myprofilebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 200, 60));

        eventbtn.setBackground(new java.awt.Color(153, 153, 153));
        eventbtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        eventbtn.setForeground(new java.awt.Color(0, 153, 255));
        eventbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AYM/view/image/pngwing.com (2).png"))); // NOI18N
        eventbtn.setText("Events ");
        eventbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventbtnActionPerformed(evt);
            }
        });
        Parentpanel.add(eventbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 170, 60));

        materialsbtn.setBackground(new java.awt.Color(153, 153, 153));
        materialsbtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        materialsbtn.setForeground(new java.awt.Color(0, 153, 255));
        materialsbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AYM/view/image/pngwing.com (4).png"))); // NOI18N
        materialsbtn.setText("AY Materials");
        materialsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialsbtnActionPerformed(evt);
            }
        });
        Parentpanel.add(materialsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 230, 60));

        logoutbtn.setBackground(new java.awt.Color(153, 153, 153));
        logoutbtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(51, 255, 102));
        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AYM/view/image/logout.png"))); // NOI18N
        logoutbtn.setText("Log Out");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        Parentpanel.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 190, 60));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Designed by");
        Parentpanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 750, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Ashimwe R Cedrick");
        Parentpanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 770, -1, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Menu");
        Parentpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AYM/view/image/backgroundfnaloriginal.png"))); // NOI18N
        Parentpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1350, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Parentpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Parentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void materialsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialsbtnActionPerformed
      materialpage mtp = new materialpage();
      mtp.setVisible(true);
    }//GEN-LAST:event_materialsbtnActionPerformed

    private void myprofilebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myprofilebtnMouseClicked
      //  alltabsstudent.setSelectedIndex(0);
    }//GEN-LAST:event_myprofilebtnMouseClicked

    private void eventbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventbtnActionPerformed
  
          eventspage evp = new eventspage();
        evp.setVisible(true);
    }//GEN-LAST:event_eventbtnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        AYMaWELCOME welcome = new AYMaWELCOME();
        welcome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homebtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
       AYMLOGIN login = new AYMLOGIN();
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void myprofilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myprofilebtnActionPerformed
        myprofilepage myp = new myprofilepage();
        myp.setVisible(true);
    }//GEN-LAST:event_myprofilebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegularUserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegularUserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegularUserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegularUserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegularUserDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Parentpanel;
    private javax.swing.JButton eventbtn;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton materialsbtn;
    private javax.swing.JButton myprofilebtn;
    // End of variables declaration//GEN-END:variables
}
